---
version: "3"
services:
  flaresolverr:
    build: .
    container_name: flaresolverr
    network_mode: host
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Moscow
      - LANG=ru_RU
      - USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
